### ISSUE TITLE
Background fetching of data and general workflow question

### ISSUE THREAD

**Issue by samducker** [gitn00b1337/expo-widgets#31]
Hi so I managed to get the example repo to run, and using the example! Thanks for the library.

I have a couple of questions probably some that will seem stupid apologies!

- Is my best method to refresh background data to use the setWidgetData function on the JS side in combination with https://docs.expo.dev/versions/latest/sdk/background-fetch/ ?
- Or do I need to follow using the timeline provider approach on the swift side? (not a swift developer just watching some videos!)
- Workflow wise should I run npx expo ios then open xcode and run the build from there? Should I develop the widget in isolation outside of the project in xcode? What is the best practical way to work on my widget.

**Comment by gitn00b1337** [comment]
Hi

For the data, I would recommend timeline. For the workflow, it's personal preference. Personally I use a separate project because if you forget copy code from the iOS folder back to your widget folder and run a new prebuild, it's all lost. If I ever get the time I'll build a syncing tool to make it easier

**Comment by gitn00b1337** [comment]
Think this is sorted, email me if you have any questions
